version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: "pc-node_server_1"
      APP_PORT: 19044

  server:
    image: "peercoin/peercoin:0.22.1"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/data:/home/peercoin/.peercoin"
    ports:
      - "19044:19044"
      - "19045:19045"
