version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: peercoin_node
      APP_PORT: 9902

  peercoin_node:
    image: peercoin/peercoind:latest
    container_name: peercoin_node
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - "9901:9901"
      - "9902:9902"
    environment:
      - PPC_DATA=/data
    command:
      -rpcallowip=0.0.0.0/0
      -rpcuser=umbrel
      -rpcpassword=moneyprinter
      -server=1
      -printtoconsole
